project:
  type: default
  title: "Présentation quarto-Insee"
  output-dir: _output
  resources:
    - "_extensions/"
    - "css/"
    - "data/"
    - "img/"
    - "videos/"
    - "js/"
    - "R/"
    - "modulesCompl/"
    - "*.html"
    - "*_files/"
  render:
    - "*.qmd"
    - "!R/data.qmd"
    
format:
  insee-clair-revealjs: default
  insee-clair-odt: default
  
fig-cap-location: bottom

from: markdown+emoji
lang: "fr"

execute:
  echo: false
  cache: false
  message: false
  warning: false
  error: true

revealjs-plugins:
  - pointer
  - confetti
  - verticator
  - multimodal