project:
  type: default
  title: "Présentation quarto-Insee"
  render:
    - "index.qmd"

format:
  insee-clair-revealjs: default

fig-cap-location: bottom

from: markdown+emoji
lang: "fr"

execute:
  echo: false
  cache: false
  message: false
  warning: false
  error: true
